<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "car".
 *
 * @property string $id
 * @property string $customer_id
 * @property string $model_id
 * @property string $vin
 * @property integer $year
 * @property string $comment
 * @property integer $deleted
 *
 * @property \common\models\CarModel $model
 * @property \common\models\Customer $customer
 * @property string $aliasModel
 */
abstract class Car extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'car';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id'], 'required'],
            [['customer_id', 'model_id', 'year', 'deleted'], 'integer'],
            [['comment'], 'string'],
            [['vin'], 'string', 'max' => 17],
            [['model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\CarModel::className(), 'targetAttribute' => ['model_id' => 'id']],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Customer::className(), 'targetAttribute' => ['customer_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'model_id' => 'Model ID',
            'vin' => 'Vin',
            'year' => 'Year',
            'comment' => 'Comment',
            'deleted' => 'Deleted',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModel()
    {
        return $this->hasOne(\common\models\CarModel::className(), ['id' => 'model_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\common\models\Customer::className(), ['id' => 'customer_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\Car the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\Car(get_called_class());
    }


}
