<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "car_firm".
 *
 * @property string $id
 * @property string $name
 *
 * @property \common\models\CarModel[] $carModels
 * @property string $aliasModel
 */
abstract class CarFirm extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'car_firm';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 20],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarModels()
    {
        return $this->hasMany(\common\models\CarModel::className(), ['firm_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CarFirmQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CarFirmQuery(get_called_class());
    }


}
