<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "car_model".
 *
 * @property string $id
 * @property string $firm_id
 * @property string $name
 * @property integer $year_begin
 * @property integer $year_end
 * @property string $comment
 * @property integer $deleted
 *
 * @property \common\models\Car[] $cars
 * @property \common\models\CarFirm $firm
 * @property string $aliasModel
 */
abstract class CarModel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'car_model';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['firm_id', 'name'], 'required'],
            [['firm_id', 'year_begin', 'year_end', 'deleted'], 'integer'],
            [['comment'], 'string'],
            [['name'], 'string', 'max' => 30],
            [['name'], 'unique'],
            [['firm_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\CarFirm::className(), 'targetAttribute' => ['firm_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'firm_id' => 'Firm ID',
            'name' => 'Name',
            'year_begin' => 'Year Begin',
            'year_end' => 'Year End',
            'comment' => 'Comment',
            'deleted' => 'Deleted',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCars()
    {
        return $this->hasMany(\common\models\Car::className(), ['model_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFirm()
    {
        return $this->hasOne(\common\models\CarFirm::className(), ['id' => 'firm_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CarModelQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CarModelQuery(get_called_class());
    }


}
